model_opts:
  model: MASK_PCPA
  obs_input_type: [mask, local_box, pose, box, speed]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: gru
  backbone: c3d
exp_opts:
  datasets: [jaad_all, jaad_beh]
  batch_size: [1, 1]
  epochs: [20, 20]
  lr: [5.0e-05, 5.0e-05]
