model_opts:
  model: MASK_PCPA_3
  obs_input_type: [mask, local_context, pose, box, speed]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: gru
  backbone: c3d
exp_opts:
  datasets: [jaad_all, jaad_beh]
  batch_size: [2, 2]
  epochs: [40, 40]
  lr: [5.0e-07, 5.0e-07]
